// pages/index/_components/Socials.tsx
import { Index, Show } from 'solid-js';

interface SocialProps {
  data: {
    icon: string;
    link: string;
    class: string;
    text?: string;
  };
}

const SocialItem = (props: SocialProps) => {
  const { data } = props;
  return (
    <a
      class={`inline-flex px-3 py-2 mt-2 mr-2 rounded-md bg-gray-50 transition-colors decoration-none ${data.class} hover:text-white dark:bg-gray-50/10`}
      href={data.link}
      target="_blank"
    >
      <div text-xl class={data.icon} />
      <Show when={data.text}>
        <div text-sm ml-1>
          {data.text}
        </div>
      </Show>
    </a>
  );
};

export default () => {
  const socialLists = [
    {
      text: 'Blog',
      link: 'https://note.chilfish.top',
      icon: 'i-ri-book-2-line',
      class: 'hover:bg-gray-700 dark:hover:bg-white dark:hover:text-gray-900',
    },
    {
      text: '',
      link: 'https://github.com/Chilfish',
      icon: 'i-ri-github-fill',
      class: 'hover:bg-gray-700 dark:hover:bg-white dark:hover:text-gray-900',
    },
    {
      text: '',
      link: 'mailto:chill4fish@gmail.com',
      icon: 'i-ri-mail-fill',
      class: 'hover:bg-[#E84234]',
    },
    {
      text: '',
      link: 'https://twitter.com/chilllish',
      icon: 'i-fa-brands-twitter',
      class: 'hover:bg-[#00ACEE]',
    },
    {
      text: '',
      link: 'https://t.me/Chilfish',
      icon: 'i-ri-telegram-fill',
      class: 'hover:bg-[#0088CC]',
    },
    {
      text: '',
      link: 'https://discord.com/users/1039168181215961199',
      icon: 'i-ic-baseline-discord',
      class: 'hover:bg-[#5865F2]',
    },
    {
      text: '',
      link: 'https://weibo.com/chilfish',
      icon: 'i-fa-brands-weibo',
      class: 'hover:bg-[#FF8200]',
    },
    {
      text: '',
      link: 'https://space.bilibili.com/259486090',
      icon: 'i-ri-bilibili-fill',
      class: 'hover:bg-[#fb7299]',
    },
    {
      text: '',
      link: 'https://www.zhihu.com/people/Walmart_Zelo',
      icon: 'i-ri-zhihu-line',
      class: 'hover:bg-[#558EFF]',
    },
    {
      text: '',
      link: 'https://music.163.com/user/home?id=1533509979',
      icon: 'i-ri-netease-cloud-music-line',
      class: 'hover:bg-[#DD001B]',
    },
  ];

  return (
    <div my-4>
      <Index each={socialLists}>{(item) => <SocialItem data={item()} />}</Index>
    </div>
  );
};

// src/components/Socials.vue
<script setup lang="ts">
const socials = useState('socialsMap', () => [
  {
    name: 'blog',
    text: 'Blog',
    link: 'https://note.chilfish.top',
    icon: 'i-ri-book-2-line',
    class: 'hover:bg-gray-700 dark:hover:bg-white dark:hover:text-gray-900',
  },
  {
    name: 'github',
    text: '',
    link: 'https://github.com/Chilfish',
    icon: 'i-ri-github-fill',
    class: 'hover:bg-gray-700 dark:hover:bg-white dark:hover:text-gray-900',
  },
  {
    name: 'mail',
    text: '',
    link: 'mailto:chill4fish@gmail.com',
    icon: 'i-ri-mail-fill',
    class: 'hover:bg-[#E84234]',
  },
  {
    name: 'twitter',
    text: '',
    link: 'https://twitter.com/chilllish',
    icon: 'i-fa-brands-twitter',
    class: 'hover:bg-[#00ACEE]',
  },
  {
    name: 'tel',
    text: '',
    link: 'https://t.me/Chilfish',
    icon: 'i-ri-telegram-fill',
    class: 'hover:bg-[#0088CC]',
  },
  {
    name: 'discord',
    text: '',
    link: 'https://discord.com/users/1039168181215961199',
    icon: 'i-ic-baseline-discord',
    class: 'hover:bg-[#5865F2]',
  },
  {
    name: 'weibo',
    text: '',
    link: 'https://weibo.com/chilfish',
    icon: 'i-fa-brands-weibo',
    class: 'hover:bg-[#FF8200]',
  },
  {
    name: 'bili',
    text: '',
    link: 'https://space.bilibili.com/259486090',
    icon: 'i-ri-bilibili-fill',
    class: 'hover:bg-[#fb7299]',
  },
  {
    name: 'zhihu',
    text: '',
    link: 'https://www.zhihu.com/people/Walmart_Zelo',
    icon: 'i-ri-zhihu-line',
    class: 'hover:bg-[#558EFF]',
  },
  {
    name: '163',
    text: '',
    link: 'https://music.163.com/user/home?id=1533509979',
    icon: 'i-ri-netease-cloud-music-line',
    class: 'hover:bg-[#DD001B]',
  },
])
</script>

<template>
  <div>
    <a
      v-for="social in socials" :key="social.name"
      class="mr-2 mt-2 inline-flex rounded-md bg-gray-8 px-3 py-2 text-center decoration-none transition-colors hover:text-white"

      :class="social.class"
      :href="social.link"
      target="_blank"
    >
      <div
        :class="social.icon"
        class="text-xl"
      />
      <div
        v-if="social.text"
        class="ml-1 text-sm"
      >{{ social.text }}</div>
    </a>
  </div>
</template>
